export enum AuctionErrorMessage {
  AUCTION_NOT_FOUND = 'Auction not found',
  AUCTION_CLOSED = 'Auction closed',
  INVALID_FIND_AUCTION_ARGS = 'Invalid find auction args',
  BID_NOT_FOUND = 'Bid not found',
  BID_FROM_SELLER_ERROR = 'Bid from seller not allowed',
  BID_BELOW_THE_CURRENT_PRICE = 'Bid below the current price',
  CANCELLERS_ATTEMPT_TO_RE_BID = 'Cancellers attempt to re-bid',
  BID_CANCELLATION_TIMEOUT = 'Bid cancellation Timeout',
  AUCTION_CREATION_FAILED = 'Auction creation failed',
  AUCTION_UPDATE_REQUEST_FROM_UNAUTHORIZED_USER = 'Auction update request from unauthorized user',
  BID_CREATION_FAILED = 'Bid creation failed',
  BID_CANCELLATION_TARGET_IS_NOT_A_RECENT_BID = 'Bid cancellation target is not a recent bid',
  PLACE_BID_RETRY_LIMIT_EXCEEDED = 'Failed to place bid after multiple attempts due to version conflict',
  SERVER_MAINTENANCE = 'The server is currently under maintenance. Please try again later.',
}
