schema:
  - 'http://127.0.0.1:8080/graphql'
documents:
  - './lib/graphql/**/*.graphql'
generates:
  ./generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withResultType: true
      withHooks: true